# Generated by Django 4.1 on 2025-07-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='aadhaar_no',
            new_name='aadhaar',
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
