# Generated by Django 4.1 on 2025-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_aadhaar_no_customuser_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seat_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
