# Generated by Django 4.1 on 2025-07-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passenger_seat_no_alter_passenger_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seat_no',
            field=models.CharField(default='S1', max_length=10),
        ),
    ]
