# Generated by Django 4.1 on 2025-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_code'], name='core_bookin_booking_e2bb0a_idx'),
        ),
    ]
