# Generated by Django 4.1 on 2025-07-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_booking_booking_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='seat_no',
            new_name='seat_number',
        ),
    ]
