# Generated by Django 4.1 on 2025-07-07 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_passenger_seat_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together={('seat_number', 'booking')},
        ),
    ]
